#!/usr/bin/env python

#-----------------------------------------------------------------------------
# Main program
#-----------------------------------------------------------------------------
import sys
inP=sys.argv

if len(inP)<=3:
    print("Invalid input. Correct promt: ./Project8.py <Height> <Length> <File>")
    sys.exit()
else:
    try: int(inP[1]) ; int(inP[2]);pass
    except:
        print("Invalid Height or Length. Correct promt: ./Project8.py <positive interger> <positive interger> <File>")
        sys.exit()
if int(inP[1])<=0 or int(inP[2]) <=0:
    print("Negative Height or Length. Correct promt: ./Project8.py <positive interger> <positive interger> <File>")
    sys.exit()
elif int(inP[1])<10 or int(inP[2])<10:
    print("Value to small for Height or Length. Put value that is larger than 10")
    sys.exit()
else:
    pass
h=int(inP[1])
l=int(inP[2])
try:
    with open(inP[3],'r') as e:
        pass
except:
    print("Error. File not found or file cannot be read")
    sys.exit()
f=open(inP[3],"r") ; line=f.readlines(0)
pos=[int(h//2+1),int(l//2+1)]
direction={'n':1.0,"e":1,"s":-1.0,"w":-1}
line=line[0]
count=0
count1=0
for i in line:
    print(i)
    if i!="n" and i!="w" and i!="s" and i!="e":
        print(i)
        print("Error. Corrupted File")
        sys.exit()        
for i in line:
    print("--",i)
    if pos[0]==1 or pos[0]==h or pos[1]==1 or pos[1]==l:
        if (h//2)-1<pos[0]<(h//2)+3:
            print("The walk was "+str(count1)+" steps long return to the origin "+str(count)+" times. It ended because it get to the gate")
            break
        else:
            print("The walk was "+str(count1)+" steps long return to the origin "+str(count)+" times. It ended because it get to the wall")        
            break
    result=direction.get(i)
    count1=count+1
    if isinstance(result, int):
        pos[1]=pos[1]+int(result)
    elif isinstance(result, float):
        pos[0]=pos[0]+int(result)
    else:
        pass
    if pos[0]==int(h//2+1) and pos[1]==int(l//2+1):
        count=1+count
    else:
        pass
    
